djangocms_charts/urls.py
from django.urls import path
from djangocms_charts.views import get_chart_as_json, get_global_options_as_json


app_name = 'djangocms_charts'


urlpatterns = [
    path('get_chart_as_json/<int:chart_id>/', get_chart_as_json, name="get_chart_as_json"),
    path('get_global_options_as_json/<int:options_id>/', get_global_options_as_json, name="get_global_options_as_json"),
]

djangocms_charts/forms.py
import csv
import io
import json
from django_select2.forms import Select2Widget
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import ModelForm
from django.utils.translation import ugettext_lazy as _

from djangocms_charts.consts import get_chartjs_global_options, OPTION_DATA_TYPES, get_chartjs_dataset_options, \
    get_chartjs_chart_options, get_chartjs_axis_options, CHART_TYPES, COLOR_LABELS
from djangocms_charts.widgets import *
from djangocms_charts.utils import *


class OptionsInlineFormBase(ModelForm):
    type = forms.CharField(required=True,  widget=forms.Select(choices=OPTION_DATA_TYPES))
    value = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))

    def clean(self):
        cleaned_data = super().clean()
        val = cleaned_data.get('value')
        val_type = cleaned_data.get('type')
        try:
            check_val = self.instance.get_json_value(val, val_type)
        except Exception as err:
            raise ValidationError(
                _('Invalid value: %(value)s'),
                code='invalid',
                params={'value': val},
            )

    class Media:
        js = (
            'djangocms_charts/input/js/jquery-3.5.1.min.js',
            'djangocms_charts/input/custom/admin_fixes.js',
        )

        css = {
            'all': (
                'djangocms_charts/input/custom/admin_styles.css',
            )
        }

# Option Forms with different inputs:

class GlobalOptionsInlineForm(OptionsInlineFormBase):
    label = forms.CharField(required=True, widget=Select2Widget(choices=get_chartjs_global_options()))


class ChartOptionsInlineForm(OptionsInlineFormBase):
    label = forms.CharField(required=True, widget=Select2Widget(choices=get_chartjs_chart_options()))


class DatasetOptionsInlineForm(OptionsInlineFormBase):
    label = forms.CharField(required=True, widget=Select2Widget(choices=get_chartjs_dataset_options()))


class AxisOptionsInlineForm(OptionsInlineFormBase):
    label = forms.CharField(required=True, widget=Select2Widget(choices=get_chartjs_axis_options()))


# Dataset form

class DatasetInputForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(DatasetInputForm, self).__init__(*args, **kwargs)

    caption = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))

    # Table input / csv upload
    table_data = forms.CharField(widget=InputTableWidget)
    csv_upload = forms.FileField(label=_("upload .csv file"), help_text=_("Upload a .csv file to populate the table."), required=False)

    # Add the cleaned csv data to the table
    def clean_table_data(self):
        if self.cleaned_data['table_data']:
            table_data = json.loads(self.cleaned_data['table_data'])

            # Check for empty rows
            data_check_rows = []
            for row in table_data:
                row_check = False
                for cell in row:
                    if cell:
                        row_check = True
                        break
                if row_check :
                    data_check_rows.append(row)

            # Check for empty cols
            data_check_cols=[]
            data_check_rows = transpose(data_check_rows)
            for col in data_check_rows:
                col_check = False
                for cell in col:
                    if cell:
                        col_check = True
                        break
                if col_check :
                    data_check_cols.append(col)
            data_check_cols = transpose(data_check_cols)

            return json.dumps(list(data_check_cols))


    # Add the cleaned csv data to the table
    def clean_csv_upload(self):
        if self.cleaned_data['csv_upload']:
            encoding = self.cleaned_data['csv_upload'].charset if self.cleaned_data['csv_upload'].charset else 'utf-8-sig'
            f = io.TextIOWrapper(self.cleaned_data['csv_upload'].file, encoding=encoding)
            csv_reader = csv.reader(f, dialect='excel')
            data = []
            for row in csv_reader:
                data.append(row)
            self.cleaned_data['table_data'] = json.dumps(data)
            self.csv_uploaded = True


    def clean(self):
        cleaned_data = super().clean()
        table_data = cleaned_data.get("table_data")
        check_data = json.loads(table_data)
        if not check_data:
            raise ValidationError("Error: missing chart data from table or CSV file input")

    class Meta:
        labels = {
            'dataset_options_group': _('Dataset options'),
        }



# Color Inline input form
# ------------------------

class ColorInputForm(ModelForm):
    types = forms.MultipleChoiceField(label=_('Select Chart Types'), help_text=_('Hold CTRL for multiple values'),
                                      choices=CHART_TYPES.get_choices)
    labels = forms.MultipleChoiceField(label=_('Select Namespace Labels'), help_text=_('Hold CTRL for multiple values'),
                                       choices=COLOR_LABELS)
    colors = forms.CharField(label=_('Select Colors for each dataset'), widget=MultiColorSelectWidget,
                             help_text=_('Click and drag changes to change order, or enter manually'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.initial and self.initial['types']:
            self.initial['types'] = json.loads(self.initial['types'].replace("'", '"'))
        if self.initial and self.initial['labels']:
            self.initial['labels'] = json.loads(self.initial['labels'].replace("'", '"'))

djangocms_charts/templates/djangocms_charts/widgets/input-table.html
<div id="input-table"></div>

<script>

    //Set Rendering Functions for Labels or Values
    //*******************************************
    var labelRenderer = function (instance, td, row, col, prop, value, cellProperties) {
        Handsontable.TextCell.renderer.apply(this, arguments);
        td.style.background = '#EAEAEA';
        td.style.fontWeight = 'bold';
        td.style.textAlign = 'center';
    };

    var valueRenderer = function (instance, td, row, col, prop, value, cellProperties) {
        Handsontable.TextCell.renderer.apply(this, arguments);
        td.style.background = 'white !important';
        td.style.fontWeight = 'normal !important';
    };


    //Get the data as a two columns or full data
    //*******************************************
    function array_resize(the_data, num_cols=0, num_rows=0) {
        if(!the_data) return;
        //Get number of cols, less than current gets reduced, more get's a blank array concatenated
        if(num_cols > 0) {
            num_cols = num_cols ? num_cols : the_data[0].length;
            add_cols = Math.max(0, num_cols - the_data[0].length);
            append_cols = new Array(add_cols);
            the_data = the_data.map(function (the_row) {
                return the_row.slice(0, num_cols).concat(append_cols);
            });
        }
        if(num_rows > 0){
            num_rows = num_rows ? num_rows : the_data.length;
            add_rows = Math.max(0, num_rows - the_data.length);
            if (add_rows > 0) {
                append_rows = new Array(add_rows).map(() => new Array(the_data[0].length));
                the_data = the_data.concat(append_rows);
            }
            the_data = the_data.slice(0, num_rows);
        }
        return the_data;
    }

    //Get the options based on Chart Type
    //*******************************************
    function get_table_options(table_data, $chart_type, $labels_top, $labels_left, $data_series_format, change_function) {
        var options = {

            //Common Settings
            // ---------------------------
            rowHeaders: true,
            colHeaders: true,
            contextMenu: false,
            startRows: 5,
            minRows: 1,
            minCols: 1,
            manualColumnResize: true,

            // On Change write the data as json
            // ---------------------------
            afterChange: function (change, source) {
                change_function();
            },
            afterRender: function () {
                change_function();
            },

            //Format each cell based on label/value renderer
            // ---------------------------
            cells: function (row, col, prop) {

                var cellProperties = {};

                //If Label then set to grey background and text input
                if ((row === 0 && $labels_top.is(':checked')) || (col === 0 && $labels_left.is(':checked'))) {
                    cellProperties = {
                        type: 'text',
                        renderer: labelRenderer,
                        validator: undefined //must be set explicitly as handsontable isn't working!
                    };
                    //If Input values then must be numeric for chart
                } else {
                    cellProperties = {
                        type: 'numeric',
                        renderer: valueRenderer
                    };
                }
                return cellProperties;
            }
        };

        if($.inArray($chart_type.val(), ['scatter', 'line_xy', 'bubble']) > -1) {

            // X, Y, [R] - Coordinate Cols
            // ---------------------------

            //Get data as a 2 or 3 column array only
            // ---------------------------
            var rows_cols_required = ($chart_type.val() === 'bubble') ? 3 : 2;
            required_labels = ['x', 'y', 'r'].slice(0, rows_cols_required);

            if($data_series_format.val() === 'rows') {
                if($labels_left.prop('checked')) {
                    required_labels.unshift("");
                    rows_cols_required += 1;
                }
                options['data'] = array_resize(table_data, rows_cols_required);
                options['colHeaders'] = required_labels;
                options['rowHeaders'] = true;
                options['startCols'] = rows_cols_required;
                options['contextMenu'] = ['undo', 'redo', '---------', 'row_above', 'row_below', 'remove_row'];
            } else {
                if($labels_top.prop('checked')) {
                    required_labels.unshift("");
                    rows_cols_required += 1;
                }
                options['data'] = array_resize(table_data, 0, rows_cols_required);
                options['rowHeaders'] = required_labels;
                options['colHeaders'] = true;
                options['startRows'] = rows_cols_required;
                options['contextMenu'] = ['undo', 'redo', '---------', 'col_left', 'col_right', 'remove_col'];
            }

        } else {

            // Label - Value Data Series Cols
            // ---------------------------

            //Get data as original loaded data
            // ---------------------------
            options['data'] = table_data;

            //Set options for all other types of charts
            // ---------------------------
            options['colHeaders'] = true;
            options['columns'] = null;
            options['startCols'] = 5;
            options['contextMenu'] = ['undo', 'redo', '---------',
                'row_above', 'row_below', 'remove_row', '---------',
                'col_left', 'col_right', 'remove_col'];
        }
        return options;
    }

</script>

<script>

    (function ($) {

        $(document).ready(function () {

            // Get Form Input Objects
            //*******************************************
            var $chart_type = $("#id_type");
            var $labels_top = $("#id_labels_top");
            var $labels_left = $("#id_labels_left");
            var $data_series_format = $("#id_data_series_format");
            var $output_field = $("#id_{{ name }}");

            // Load original data if exists
            //*******************************************
            var table_data = {{ data|default:"null"|safe }};

            //Get Chart types and set headers, input table container etc.
            //*******************************************
            var input_table_container = document.getElementById("input-table");
            var input_table;


            //Build Table
            //*******************************************
            build_table();

            function build_table() {
                var table_options = get_table_options(table_data, $chart_type, $labels_top, $labels_left, $data_series_format, output_data_to_dom);
                // Remove existing Input table if exists
                if (input_table !== undefined && input_table.table != null) {
                    input_table.destroy();
                    input_table = undefined;
                }
                // Build new input table
                input_table = new Handsontable(input_table_container, table_options);
                output_data_to_dom();
                validate_and_render();
            }

            // Reformat table on change of rows/cols labels
            //*******************************************
            function validate_and_render() {
                if(input_table !== undefined) {
                    input_table.validateCells();
                    input_table.render();
                }
            }

            //Output the table data on change or rebuild to the django div for save/loading.
            //*******************************************
            function output_data_to_dom(){
                if (input_table !== undefined) {
                    table_data = input_table.getData();
                }
                $output_field.val(JSON.stringify(table_data));
            }

            //On change of Type Header Labels - update validation and render table
            //*******************************************
            $($chart_type).add($($labels_left)).add($labels_top).add($data_series_format).change(function () {
                build_table();
            });

            //On change of Chart Type - update table completely
            //*******************************************
            $($chart_type).change(function () {
                build_table();
            });

        });
    })(jQuery);


    //]]>
</script>
<style type="text/css">
    {# Hide the original Text field  #}
    #id_{{ name }} {
        display: none !important;
    }
</style>

djangocms_charts/templates/djangocms_charts/widgets/multi-color-select.html
{% load sekizai_tags %}

{# Multiple Colour widget #}
<div class="multiple-color-widget">
    {# Default Django input field #}
    <input type="text"
           class="mutiple-color-input"
           id="{{ widget.attrs.id }}"
           name="{{ widget.name }}"
           value="{% firstof widget.value widget.attrs.default '' %}"
           placeholder="{% firstof widget.attrs.default '' %}"
           style="width: 100%!important;"
           {% if widget.attrs.required %}required{% endif %}/>

    {# Color Select List and Add Button  #}
    <ul class="multiple-color-list">
    </ul>
    <button class="btn btn-default multiple-color-add-button" role="button">Add new color</button>

    {# Template used to add new colors   #}
    <template class="multiple-color-template">
        <li class="input-group">
            <input class="multiple-color-input" type="color" style="width: 75px!important;">
            <button class="multiple-color-remove-button">&times;</button>
        </li>
    </template>
</div>